filecoin-station/desktop

package-lock.json
package.json
src/index.js
src/tray.js
src/updater.js
test/e2e/example.e2e.test.js

feat: basic e2e test setup

---

package-lock.json
package.json
src/index.js
src/store.js
src/tray.js
src/typings.d.ts
src/ui.js
src/updater.js
test/e2e/example.e2e.test.js
tsconfig.json

Enable TypeScript checking of JS files

---

package-lock.json
package.json

- deps: upgrade electron to 19.0.2
- deps: lock-file maintenance

deps: upgrade electron to v19 + lockfile maintenance

---

docs/DEVELOPING.md

docs: add more content to Developer Guide

---

docs/DEVELOPING.md
main/ui.js
package-lock.json
package.json
renderer/src/App.css
renderer/src/Saturn.tsx
test/e2e/app-launch.e2e.test.js

feat: render Saturn L2 webui

---

main/ipc.js
main/preload.js
main/saturn-node.js
renderer/src/Saturn.css
renderer/src/Saturn.tsx
renderer/src/typings.d.ts

- Build a log of Saturn Node state changes and errors
- When the node is not running, show the log in the UI
See #44

feat: show Saturn Node startup errors

---

.eslintrc.json
build/download-saturn-l2.js
main/ipc.js
main/preload.js
main/saturn-node.js
package-lock.json
package.json
renderer/src/App.css
renderer/src/App.tsx
renderer/src/Saturn.css
renderer/src/Saturn.tsx
renderer/src/components/FilAddressForm.tsx
renderer/src/typings.d.ts
test/e2e/app-launch.e2e.test.js

- feat: upgrade saturn-l2 to v0.0.5
- feat: configure FIL Wallet Addres for Saturn
Close #44

Upgrade Saturn + configure FIL Address

---

.github/workflows/ci.yml
.prettierignore
.prettierrc.yaml
README.md
SECURITY.md
docs/DEVELOPING.md
docs/RELEASE_PROCESS.md
docs/architecture-decision-records/2022-07-module-configuration.md
docs/architecture-decision-records/template.md
package-lock.json
package.json

- chore: enable Prettier for Markdown files
- build: disable git's autocrlf on Windows CI
- docs: template for Architecture Decision Records
- docs: add Module Configuration ADR

ADR: Module Configuration

---

build/download-saturn-l2.js
main/consts.js
main/saturn-node.js

- feat: upgrade Saturn L2 Node to v0.0.8
- feat: configure `ROOT_DIR` for Saturn L2
Close #56

Upgrade Saturn L2 to v0.0.8 and configure ROOT_DIR

---

package-lock.json
package.json

- `electron` 20.x
- `vite` 3.x
- `@vitejs/plugin-react` 2.x

deps: update to latest

---

.github/dependabot.yml
.github/workflows/dependabot-auto-merge.yml

- chore: tweak dependabot commit messages
- build: auto-merge dependabot pull requests

Improve Dependabot setup

---

main/ipc.js
main/preload.js
main/station-config.js
renderer/src/Saturn.tsx
renderer/src/typings.d.ts

Electron interface to store usage info: 
- Station fil address
- Station user saw onboarding
- Station user consent

Station-wide config options - storage & IPC

---

build/download-saturn-l2.js

Get additional Activities reported to The station.
Screenshot from the app:
See also #81

feat: upgrade Saturn L2 Node to v0.4.1

---

build/before-pack.js
electron-builder.yml
main/consts.js
main/index.js
main/preload.js
package-lock.json
package.json
renderer/src/main.tsx
renderer/src/typings.d.ts

See #78
- feat: setup Sentry error monitoring
- feat: add release to Sentry config
Out of scope:
- Report releases and source maps to Sentry
- Report errors from the backend

feat: basic Sentry error monitoring

---

package-lock.json
package.json
renderer/index.html
renderer/src/App.tsx
renderer/src/Saturn.tsx
renderer/src/components/Plausible.tsx
renderer/src/components/Sentry.tsx
renderer/src/main.tsx

Partially handles #118, as we don't have Telemetry yet

Add load scripts after consent #118

---

renderer/src/App.tsx
renderer/src/Saturn.tsx
renderer/src/pages/Onboarding.tsx
renderer/src/pages/WalletConfig.tsx
test/e2e/app-launch.e2e.test.js

Anything but "Filecoin Station" is usually not what you expect from a desktop application.

fix remove dynamic window title

---

renderer/src/App.css
renderer/src/pages/Dashboard.tsx

Following #173, this PR adds the css for making everything a drag point for the window. This excludes actionable and text elements such as forms, buttons, as well as onboarding slider box and activity items.
Closes #173

Move station window. Closes #173

---

.github/workflows/ci.yml
renderer/src/test/dashboard.test.tsx
vite.config.js

This PR implements an hotfix to frontend tests. 
Further inspection is required.

fixup: blocking tests

---

main/test/test-helpers.js

ref https://github.com/filecoin-project/filecoin-station/actions/runs/3151310797/jobs/5125102474

fix flaky tests on macOS

---

main/ui.js
renderer/src/components/Onboarding.tsx
renderer/src/pages/WalletConfig.tsx

Closes #159.
This PR defines the minimum window size for the application and reviews some div's `min` and `max` widths, as the first iteration about responsivity. 
Here are some screenshots

Add responsive design. Closes #159

---

renderer/src/pages/Dashboard.tsx

Closes #195
This PR fixes the behaviour on activity log scroll

Fix activity log scroll

---

main/app-menu.js
main/index.js

Fix app menu on windows and linux

---

main/saturn-node.js

Fix saturn log buffer overflow. Closes #211

---

electron-builder.yml

Remove version from artifact. Closes #221

---

main/dialog.js
renderer/src/App.css
renderer/src/assets/img/arrow-left.svg
renderer/src/components/FilAddressForm.tsx
renderer/src/components/Onboarding.tsx
renderer/src/pages/Dashboard.tsx
renderer/src/pages/Onboarding.tsx
renderer/src/pages/WalletConfig.tsx
renderer/src/test/onboarding.test.tsx

Closes #225
This PR adds the first reviewed version of copy and some tweaks on CSS to better fit the copy in the containers.

feat: review app copy

---

renderer/src/components/UpdateBanner.tsx

https://www.notion.so/Desktop-app-content-1545b042618a464ea9a91189fdf870c7#4e389ac366c245d28368b439294145c0

UpdateBanner: Update copy

---

main/saturn-node.js

Add report Sentry exit errors to Sentry. Closes #247

---

renderer/src/pages/Dashboard.tsx

Improvement on the `Dashboard` page codebase as suggested on [#199 comment](https://github.com/filecoin-station/filecoin-station/pull/199#discussion_r989098138)
Parallelization of stored data requests

Refactor dashboard initialization

---

package-lock.json
package.json

```
"@sentry/node": "^7.21.1",
"@sentry/react": "^7.21.1",
"@sentry/tracing": "^7.21.1",
```

deps: update Sentry to 7.21.1

---

package-lock.json
package.json

```
npm i '@sentry/node@latest' '@sentry/react@latest' '@sentry/tracing@latest'
```

deps: update Sentry to 7.26.0

---

renderer/src/assets/img/icons/copy.svg
renderer/src/components/FilAddressForm.tsx
renderer/src/components/WalletModule.tsx

- Hide the internal station address
- Add button to copy internal station address to clipboard
- Hide the destination address

Hide parts of destination address

---

.eslintrc.json
package-lock.json
package.json
renderer/src/components/Onboarding.tsx

Blocks https://github.com/filecoin-station/filecoin-station/pull/420

Add `eslint-plugin-react`

---

main/wallet-backend.js
package-lock.json
package.json

@bajtos I didn't mean to add `node-fetch` when we already have `undici`, and +1 to using it as the default now

replace `node-fetch` with `undici`

---

.github/workflows/ci.yml

See eg https://github.com/filecoin-station/filecoin-station/actions/runs/4192353583/jobs/7267991425
We were missing the windows cert inputs.

Fix windows building

---

renderer/src/components/WalletOnboarding.tsx
renderer/src/components/WalletTransactionsHistory.tsx

fixup: wallet onboarding scroll closes #484

---

renderer/src/components/FilAddressForm.tsx
renderer/src/components/TransferFunds.tsx

fixup: animation time and opacity - closes #527

---

.eslintrc.json
renderer/src/components/FilAddressForm.tsx
renderer/src/components/Modal.tsx
renderer/src/components/Onboarding.tsx
renderer/src/components/TransferFunds.tsx
renderer/src/components/WalletModule.tsx
renderer/src/components/WalletOnboarding.tsx
renderer/src/components/WalletTransactionStatusWidget.tsx
renderer/src/components/WalletTransactionsHistory.tsx
renderer/src/components/WalletWidget.tsx
renderer/src/hooks/StationWallet.tsx
renderer/src/lib/station-config.tsx
renderer/src/pages/Dashboard.tsx
renderer/src/test/dashboard.test.tsx
renderer/src/test/onboarding.test.tsx
renderer/src/test/wallet.test.tsx
renderer/src/typings.ts

115 characters is the maximum line length (for me) that GitHub can display without scrolling horizontally.

set project max line length to 115

---

README.md

https://protocol-labs-ip.sentry.io/issues/3974435454/?project=6762462&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d
From https://github.com/atom/node-keytar

docs: libsecret

---

main/telemetry.js

For tracking how updates are rolled out
https://github.com/filecoin-station/core/pull/51

telemetry: add `version`

---

main/test/wallet.test.js
main/typings.d.ts
main/wallet-backend.js
renderer/src/components/ActivityLog.tsx
renderer/src/hooks/StationActivity.tsx
renderer/src/lib/station-config.tsx
renderer/src/typings.ts
shared/typings.d.ts

Pulling the shared types into a common file
Closes #445

DRY types. Closes #445

---

main/telemetry.js

For https://github.com/filecoin-station/core/pull/66#discussion_r1146124578

telemetry: add `arch`

---

main/core.js
package-lock.json
package.json

For https://github.com/filecoin-station/core/pull/132

core: Add pass `RUNNING_IN_STATION_DESKTOP`

---

.github/workflows/ci.yml
build/notarize-macos.js

As mentioned via Email by @bajtos 🙏

Update use `notarytool` for notarization

---

package-lock.json
package.json
renderer/src/App.css

This release has the latest currently available security patches (see https://github.com/electron/electron/releases?page=1)
I took another look at upgrading to 23 and beyond, but couldn't yet figure out the click issues.

upgrade to latest electron

---

package-lock.json
package.json

https://github.com/filecoin-station/core/releases/tag/v14.2.0

deps: bump @filecoin-station/core to 14.2.0

---

package-lock.json
package.json

https://github.com/filecoin-station/core/releases/tag/v14.3.0

feat: upgrade Station Core to v14.3.0

---

main/core.js
main/index.js
main/telemetry.js
main/wallet.js

Fixes #609
Alternative implementation to https://github.com/filecoin-station/desktop/pull/658, which this is based on. Thank you, @taesuklee!
Closes #658

Fix empty wallet address during keychain permission check

---

package-lock.json
package.json

See https://github.com/filecoin-station/core/releases/tag/v14.4.0

deps: bump @filecoin-station/core to 14.4.0

---

main/test/wallet-backend.test.js
main/wallet-backend.js

Closes #1034
filfox changed their response format

Wallet: fix dates. Closes #1034

---

renderer/src/components/FilAddressForm.tsx

Add reject sanctioned addresses. Closes #1074

---

main/core.js

https://protocol-labs-ip.sentry.io/issues/4643809502/?project=6762462&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

Fix network error filling up Sentry

---

package-lock.json
package.json

Links:
- https://github.com/filecoin-station/core/releases/tag/v16.3.0
- https://github.com/filecoin-station/roadmap/issues/52

feat: bump Station Core to 16.3.0

---

main/wallet-backend.js

Ref https://filecoinproject.slack.com/archives/C023K7D9GAX/p1703679868805479

Add auth to glif requests

---

main/telemetry.js

see https://github.com/filecoin-station/core/pull/334
@bajtos hindsight please

rotate telemetry token

---

electron-builder.yml
package-lock.json
package.json

Hopefully fixing the currently broken macOS builds https://github.com/filecoin-station/desktop/actions/runs/7760872900/job/21222076326

`electron-builder@24.9.1`

---

main/core.js

We used to have this because of https://github.com/filecoin-station/desktop/commit/405ada90af59c08b03fb205ca7fd90282bfbc70e#diff-a02b90930a8bd43bbbc287251cbd4d11ffaee28fd6ca97c30065ffedd0d6e325R140

core: remove unnecessary closure

---

main/ui.js

Follow up for https://github.com/filecoin-station/desktop/pull/1300, found another missing `await`.

fix missing `await` for `loadURL`. for #333

---

package-lock.json
package.json

For https://github.com/filecoin-station/roadmap/issues/85

`@filecoin-station/core@20.1.0`

---

main/ui.js
main/wallet.js

Ref https://github.com/filecoin-station/desktop/issues/1378

wallet: only update transactions when UI visible

---

.github/workflows/ci.yml

Failure first discoverd in https://github.com/filecoin-station/desktop/actions/runs/8813478455/job/24191303318?pr=1485

remove hopefully unnecessary step

---

package-lock.json
package.json
renderer/src/App.tsx
renderer/src/components/ActivityLog.tsx
renderer/src/components/FilAddressForm.tsx
renderer/src/components/Modal.tsx
renderer/src/components/Onboarding.tsx
renderer/src/components/TransferFunds.tsx
renderer/src/components/UpdateBanner.tsx
renderer/src/components/WalletModule.tsx
renderer/src/components/WalletOnboarding.tsx
renderer/src/components/WalletTransactionStatusWidget.tsx
renderer/src/components/WalletTransactionsHistory.tsx
renderer/src/components/WalletWidget.tsx
renderer/src/hooks/StationActivity.tsx
renderer/src/hooks/StationWallet.tsx
renderer/src/lib/station-config.tsx
renderer/src/pages/dashboard/Dashboard.tsx
renderer/src/pages/onboarding/Onboarding.tsx
renderer/src/test/dashboard.test.tsx
renderer/src/test/onboarding.test.tsx
renderer/src/test/wallet-interaction.test.tsx
renderer/src/test/wallet.test.tsx
renderer/tsconfig.json
vite.config.js

See https://github.com/subvisual/desktop/pull/1

Update import paths

---

package-lock.json
package.json

Release notes:
- https://github.com/filecoin-station/core/releases/tag/v20.2.0
- https://github.com/filecoin-station/core/releases/tag/v20.2.1

feat: upgrade Station Core to v20.2.1

---

renderer/src/App.tsx
renderer/src/hooks/StationModules.tsx
renderer/src/pages/modules/Modules.tsx
renderer/src/pages/modules/mockData.ts

Create unstyled modules page:
- Create mock modules data
- Create hook to fetch and return data

Add modules page

---

renderer/src/assets/img/icons/export.svg
renderer/src/assets/img/icons/save.svg
renderer/src/assets/img/icons/update.svg
renderer/src/components/BorderedBox.tsx
renderer/src/components/Layout.tsx
renderer/src/components/SwitchInput.tsx
renderer/src/components/WalletWidget.tsx
renderer/src/pages/settings/Settings.tsx
renderer/src/pages/settings/SettingsGroup.tsx
renderer/src/test/settings.test.tsx

Style settings page

---

renderer/src/hooks/StationModules.tsx
renderer/src/hooks/StationRewards.tsx
renderer/src/lib/utils.ts
renderer/src/pages/dashboard/Chart.tsx
renderer/src/pages/dashboard/ChartController.tsx
renderer/src/pages/dashboard/mockData.ts

- Add module level data in rewards mock generation. Calculate combined values on the FE
- Add chart controls for active module 
- Updated structure is:
```
{
timestamp: string;
totalRewardsReceived: Record<moduleId, number>;
totalScheduledRewards: Record<moduleId, number>;
}
```

Update rewards mock data

---

renderer/src/pages/dashboard/ChartController.tsx

Remove 1 day time range from the dashboard chart

Remove 1d time range

---

docs/architecture-decision-records/2024-04-frontend-file-structure.md

Proposal for the new file structure convention to be used for v2.

Frontend file structure proposal

---

main/wallet-backend.js

Add more context to error messages.
Before:
```
› Uncaught exception: [Error: An unknown error occurred.]
```
After:
```
› Uncaught exception: Error: Cannot read the seed phrase - did the user grant access?
at WalletBackend.getSeedPhrase (/Users/bajtos/src/filstation/desktop/main/wallet-backend.js:114:15)
at async WalletBackend.setup (/Users/bajtos/src/filstation/desktop/main/wallet-backend.js:74:26)
at async Object.setup (/Users/bajtos/src/filstation/desktop/main/wallet.js:42:25)
at async run (/Users/bajtos/src/filstation/desktop/main/index.js:169:5) {
[cause]: [Error: An unknown error occurred.]
}
```
Links:
- #1659

feat: improve logging from wallet backend

---

main/core.js

We have removed the Saturn module long time ago.

fix: remove unused saturn-l2-node migration

---

main/core.js

Print the logs to the application's log file instead of the console.
I discovered this problem while trying to debug https://github.com/filecoin-station/desktop/issues/1659

fix: use electron-log in main/core.js

---

renderer/src/pages/dashboard/ChartController.tsx

- Disable time range button when it is active
Fixes #1671

Fix deselect time range

---

renderer/src/lib/utils.ts
renderer/src/test/dashboard.test.tsx

Fix inconsistent formatting of scheduled rewards. Closes #1685

---

renderer/src/hooks/StationRewards.tsx
renderer/src/lib/utils.ts
renderer/src/pages/dashboard/Chart.tsx
renderer/src/pages/dashboard/Dashboard.tsx
renderer/src/test/dashboard.test.tsx
renderer/src/test/wallet-modal.test.tsx

Chart: Fix tooltip precision by using bigint in more places

---

main/test/wallet-backend.test.js
main/wallet-backend.js

Desktop only reads rewards from Core's output :)

Remove unused `fetchScheduledRewards()`

---

renderer/src/hooks/StationRewards.tsx
renderer/src/pages/dashboard/Chart.tsx

Fixes:
- Rewards dropping off on current day (timezone issue)
- Scheduled rewards dropping off on payout

Fix scheduled rewards rendering

---

renderer/src/hooks/StationRewards.tsx

StationRewards: fix voyager live rewards being 0

---

main/wallet-backend.js

The fixed 0.01 FIL wasn't working any more.

Fix constant gas estimate

---

.github/workflows/ci.yml
package.json

On Windows, it now throws
```
Unknown argument: onTag
```

Fix electron-builder arguments

---

FUNDING.json

See https://docs.drips.network/get-support/claim-your-repository/
Links:
- https://github.com/space-meridian/roadmap/issues/204

chore: setup Drips FUNDING.json
