README.md, SECURITY.md
Adds a  basic policy on how to report security issues.
(Copied from lotus repo)
=> docs: security policy

.github/workflows/ci.yml
Remove the following warning print by GitHub Actions when building e.g. a pull request:
```
Run dawidd6/action-get-tag@12319896edaa290b27558e34a177804e9b8d077b
Error: Not a tag ref (refs/pull/27/merge)
```
=> ci: skip "Get tag" when not building a tag

.github/workflows/ci.yml, .gitignore, build/download-saturn-l2.js, build/notarize-macos.js, electron-builder.yml, main/index.js, main/saturn-node.js, package-lock.json, package.json, tsconfig.json
- Add a build step to download Saturn L2 Node binaries from project's [GitHub Releases](https://github.com/filecoin-project/saturn-l2/releases)
- Modify Electron Builder configuration to include Saturn L2 binary in packaged Resources
- Add a dummy main script to print the path of the Saturn L2 Node binary and verify that the path exists
Close #19
=> Bundle Saturn L2 node

.github/workflows/ci.yml, docs/DEVELOPING.md, package-lock.json, package.json, test/e2e/app-launch.e2e.test.js
- Rename the script from `build:saturn` to `install-saturn`
- Run this script from `postinstall` hook
This is a follow-up for #38, see also #22
=> build: move Saturn L2 download to `postinstall`

build/download-saturn-l2.js
The project has moved to https://github.com/filecoin-saturn/L2-node
=> build: fix Saturn L2 Node repo url

main/app-menu.js, main/dialog.js, main/index.js, main/ipc.js, main/tray.js, main/typings.d.ts, main/updater.js, package-lock.json, package.json
Add "Check for Updates..." to the Tray menu. On macOS, add this item to the Application menu too. While the check is running, replace "Check for Updates" with a disabled item "Checking for Updates".
See https://github.com/filecoin-project/filecoin-station/issues/53
The implementation is heavily inspired by IPFS Desktop:
- [src/auto-updater/index.js](https://github.com/ipfs/ipfs-desktop/blob/b269cde5231915d2930eefba55b706012843a155/src/auto-updater/index.js)
- [src/tray.js](https://github.com/ipfs/ipfs-desktop/blob/b269cde5231915d2930eefba55b706012843a155/src/tray.js)
- Reworking the OS-level notification
- Showing a banner at the top of the web UI when an update is ready
A new macOS application menu item:
While checking for updates:
A new Tray menu item:
While checking for updates: …
=> feat: tray & app menu item "Check for Updates..."

.github/dependabot.yml
Another attempt to get sensible commit messages & PR titles - see https://github.com/filecoin-project/filecoin-station/pull/98#issuecomment-1237031510
I think I have originally misunderstood what `include: "scope"` means.  Apparently, the scope is "deps" or "deps-dev" for npm. We don't want such scope string in our commit messages.
In this commit, I am removing `include` config for commit messages.
See also the Dependabot code building git commit messages:
https://github.com/dependabot/dependabot-core/blob/588aa78ce05b60315e699951bb14935fa0d49230/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L74-L82
=> build: tweak Dependabot commit messages again

.eslintrc.json, build/notarize-macos.js, main/app-menu.js, main/consts.js, main/dialog.js, main/index.js, main/ipc.js, main/preload.js, main/store.js, main/test/smoke.test.js, main/tray.js, main/ui.js, main/updater.js, test/e2e/app-launch.e2e.test.js, vite.config.js
- Configure eslint to require `use strict` in all JS files
- Add missing `use strict` lines where needed
=> chore: enable strict mode in JS files

test/e2e/app-launch.e2e.test.js
Allow more time for `electron.launch` to complete when running on CI.
The goal is to fix the following CI failure:
https://github.com/filecoin-project/filecoin-station/runs/8250938538?check_suite_focus=true
=> test: fix e2e test timing out on Windows

renderer/index.html
Closes #80.
@bajtos documented these events to be captured, which I think are already covered by default:
> Modify Station UI to report the following events
> - a user starts the app (the onboarding flow)
This is a pageview on `/` or `/onboarding` or whatever we want to call the route, as long as it isn't the same URL as the dashboard. In the current version, `/` is onboarding and `/saturn` is the dashboard.
> - the user closes the app at the screen “Enter FIL”
Plausible lists "exit pages", as long as the "Enter FIL" screen has its own URL this will be taken care of already.
=> Add Plausible. Closes #80

package-lock.json, package.json
Before this change, `undici` was a dev-dependency. It was not packaged into the application. As a result, the app was crashing at startup.
This fixes the regression introduced by #136
=> fix: move `undici` to production dependencies

.eslintrc.json, package-lock.json, package.json
`eslint --fix` was unable to format these unfortunately.
=> lint: remove insufficient `"sort-import"` and `"require-sort"`

.github/workflows/ci.yml
Closes #167
<del>`npm run test:ui` currently fails, so only adding `npm run test:backend` to CI</del> UI tests have been fixed and added in https://github.com/filecoin-project/filecoin-station/pull/178
=> Fix run backend tests in CI. Closes #167

.github/workflows/ci.yml, .github/workflows/release.yml, build/before-pack.js, build/configure-sentry.js, main/build-version.js, main/consts.js
Add new CI/CD build steps to create Sentry Release entry and upload source maps.
See https://github.com/filecoin-project/filecoin-station/issues/78
Sentry docs: https://docs.sentry.io/product/cli/releases/
Initially, I started with `getsentry/action-release@v1`. Unfortunately, it does not allow us to connect custom version numbers (e.g. `0.6.0.2134`) with git commit SHAs. Thus I reworked our integration to use directly `sentry-cli`.
=> build: create Sentry releases & upload source maps

main/tray.js
- The main CTA was `Filecoin Station ${version}`, which opens a browser instead of Station. Therefore I made the first item the one to open station
- I renamed the item from `Show UI` (too technical) to `Open Station`
- The preview item `Filecoin Station ${version}` is now `Learn more...`
- I gave `Start at login` its own group, since it's the only one of its kind
Now:
Previously:
=> Update tray items

renderer/src/pages/Dashboard.tsx
Without a dependencies array, the effect was executed on every component call, instead of once initially.
=> Fix dashboard high cpu usage

main/saturn-node.js
Closes #198
One could even argue that a 1s interval is better for the user, because it makes the UI less hectic
=> Reduce saturn stats poll frequency for perf. Closes #198

.github/workflows/ci.yml
- Revert "temporarily disable step "Create Sentry Release""
- build: do not create Sentry Releases from forks
Quoting from https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow:
> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
See #78
=> Bring back Sentry Releases

docs/DEVELOPING.md, main/consts.js, main/index.js, main/station-config.js, test/e2e/app-launch.e2e.test.js
Fix the way we are determining the location of our config files and module caches when running end-to-end tests.
Before this change, E2E tests on macOS would load the configuration from user's home directory. This config typically already has the FIL wallet address configured, thus the app skips the onboarding flow, and the test suite fails.
After this change, when running the tests, the app always uses the temporary directory provided via `process.env.HOME`
=> test: use temp dir for config & cache

test/e2e/app-launch.e2e.test.js
This test is currently failing in #main. It's failing in CI, but not locally. Since we don't render Saturn's WebUI any more, I think we can just remove it without requiring further investigation.
=> Remove failing Saturn WebUI test

main/index.js
In #266, @walkerlj0 thought Station didn't open when she opened it, although it was already open (and hidden in the tray).
This change makes it so the app show its UI when you open it a second time, to try to recover from that situation.
Closes #266.
=> Fix show UI when opening Station twice. Closes #266

main/setup-sentry.js, renderer/src/components/Sentry.tsx
As a short-term fix for the broken detection of dev vs production builds (see #263), let's enable Sentry error reporting for all builds.
IMO, it's better to have some noise in our bug reports than have no errors captured at all.
=> fix: always report errors to Sentry

renderer/src/hooks/StationActivity.tsx, renderer/src/pages/Dashboard.tsx
This PR moves activity-related API calls into a dedicated hook. Also splits RPC calls into multiple `useEffect` instead of anonymous functions being called inside `Promise.all`
=> refactor: move station activity jobs rpc into hook

main/telemetry.js
It's not really actionable for us when Influx is slow or unreachable (can be either Influx or the client's connection)
=> fix unactionable Sentry errors

.github/workflows/ci.yml, build/notarize-macos.js, electron-builder.yml
- `action-electron-builder` is unmaintained &mdash; I'm a maintainer but I don't have time to pick it up again
- What it's providing isn't complex and can easily be inlined
- We need to switch from `npx` to `npm exec` for https://github.com/electron-userland/electron-builder/issues/6411, this changes prepares us for this
- The hooks weren't running - `electron-builder` is silently failing here. I've turned on `DEBUG` in the meantime, until this stabilizes
- I had to fix the `isPullRequest()` logic copied from `electron-builder`, which wasn't reading Github Actions env vars yet
- CI is passing, see the second to last commit. I had to disable the `build` step for it to pass, since there currently is a Saturn testnet issue: No nodes are available
=> Fix Electron building

electron-builder.yml
> target String | [TargetConfiguration](https://www.electron.build/cli#targetconfiguration) - The target package type: list of default, dmg, mas, mas-dev, pkg, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir. Defaults to default (dmg and zip for Squirrel.Mac). Note: Squirrel.Mac auto update mechanism requires both dmg and zip to be enabled, even when only dmg is used. Disabling zip will break auto update in dmg packages.
=> fix build .zip on mac

main/station-config.js, main/telemetry.js
`StationID` is redundant now, since every Station already has a wallet address, which is unique. Instead, add the destination wallet address as a new field, which can give us an indication of how many users we potentially have, and how many people run Station without having a destination wallet configured.
=> Update telemetry fields

main/index.js, main/saturn-node.js, main/tray.js
This is a follow-up on https://github.com/filecoin-station/filecoin-station/pull/177, where we added the tray assets, but the logic wasn't yet wired up.
This makes it so the Station tray icon changes depending on whether you're connected to the Saturn network.
=> Display tray on/off state

.eslintrc.json, main/typings.d.ts, renderer/custom.d.ts, renderer/src/components/ActivityLog.tsx, renderer/src/components/FilAddressForm.tsx, renderer/src/components/Modal.tsx, renderer/src/components/Onboarding.tsx, renderer/src/components/TransferFunds.tsx, renderer/src/components/WalletModule.tsx, renderer/src/components/WalletTransactionStatusWidget.tsx, renderer/src/components/WalletTransactionsHistory.tsx, renderer/src/components/WalletWidget.tsx, renderer/src/custom.d.ts, renderer/src/hooks/StationActivity.tsx, renderer/src/hooks/StationWallet.tsx, renderer/src/typings.ts
Closes #444
- Require semicolons as type member delimiters, as is recommended by Typescript
- Disallow semicolons as line delimiters, as is standard code style
=> Enforce consistent (no) semicolons rule in typescript definitions. Closes #444

main/saturn-node.js
I haven't looked into the specifics yet, but with most recent nodejs and electron versions, `localhost` doesn't work any more. Fix for https://github.com/filecoin-station/desktop/pull/558
=> Fix saturn connectivity

main/job-stats.js, main/telemetry.js
Previously for every job completed, we were also submitting machine info like wallet hash, operating system, etc. This has two problems:
1. When there are no jobs being completed (eg Saturn testnet traffic problem), we don't know how many Stations there are
2. There is a lot of redundant information submitted.
In this PR I'm introducing a new point `ping`, with all that meta attached, which gets submitted per Station every 10s. This can also be lowered to every 1m if we feel it's too much. In turn, the extra metadata has been removed from `jobs-completed`.
Through this, we can still construct all the queries from our stats dashboard. Some information is lost, but we hadn't used it anyway, like: how many jobs are completed per platform. If we want to add these back, we can do that, but I …
=> telemetry: add periodic `ping`, independent of jobs

main/index.js, main/telemetry.js
`os.arch()` returns `x64` when running in a translated environment on ARM64 machine, e.g. via macOS Rosetta. We don't provide Apple `arm64` builds yet.  As a result, Stations running on Apple Silicon were reporting `x64` arch.  To fix the problem, we detect `arm64` translation and report a different architecture.
I am running Station Desktop version 0.15.3 on an Apple M1 machine. Yet when I look at our Graphana Dashboard, I see that all stations run on (Intel) x64 architecture.
In the electron log file `~/Library/Logs/Filecoin Station/main.log`, I see the following lines:
```
[info]  (main)    Filecoin Station build version: 0.15.3 darwin-x64
[info]  (main)    Machine spec: Darwin version 22.4.0
```
Source code printing these lines: …
=> feat: report arch=arm64 in Rosetta 2

package.json
Sometimes old files would still be laying around, causing hard to debug issues
=> pkg: fix remove `install-core` residue

.github/dependabot.yml, .github/workflows/dependabot-auto-approve.yml
For certain packages, there's nothing to do for us as long as tests pass.
The list of package names can be extended in the future to include more safe dependencies.
=> ci: add auto approve dependabot PRs

.github/dependabot.yml
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
=> ci: add group dependabot @sentry updates

.github/workflows/dependabot-auto-approve-minor.yml, .github/workflows/dependabot-auto-approve-patch.yml
For PRs like https://github.com/filecoin-station/desktop/pull/860. In the react ecosystem it is my experience that you can trust patch updates, but should review minor updates.
=> add auto approve patch updates

package-lock.json, package.json
Revert "feat: upgrade Station Core to v14.3.0 (#1016)"
This reverts commit 5e00d1f32cca40d36d793e415270bd75a029532c.
The version v14.3.0 requires wallet address in the f4/0x format, which we don't support in Desktop yet.
=> fix: downgrade Station Core to v14.2.0

test/e2e/app-launch.e2e.test.js
- test: forward main process output to console
- test: verify that Core & Zinnia starts
Example test output with the current Core version:
```
✓  3 test/e2e/app-launch.e2e.test.js:84:3 › Application launch › renders Dashboard page (4ms)
✓  4 test/e2e/app-launch.e2e.test.js:88:3 › Application launch › wait for "Zinnia started." activity log (12ms)
Core exited via signal SIGTERM
Core closed all stdio with code <no code>
Waiting for the debugger to disconnect...
```
Example test output for Core version v14.3.0:
```
Core exited with code: 1
Core closed all stdio with code 1
✓  3 test/e2e/app-launch.e2e.test.js:84:3 › Application launch › renders Dashboard page (7ms)
✘  4 test/e2e/app-launch.e2e.test.js:88:3 › Application launch › wait for "Zinnia started." activity log (1.0s)
Waiting for the …
```
=> test: verify that Core & Zinnia starts

renderer/src/pages/Dashboard.tsx
=> fix: formatting of tooltip for scheduled rewards

main/test/wallet-backend.test.js
The seed used for testing `fetchAllTransactions` is used in other places, too and as a result, the address has some rewards accrued in the contract.
That breaks the test for `fetchScheduledRewards`.
This commit fixes the problem by generating a new random wallet seed for this test.
=> test: change wallet for testing scheduled rewards

main/wallet.js, renderer/src/pages/Dashboard.tsx
- refactor: consistent format of scheduled rewards
- fix: less space between the rewards and the unit
- feat: show only 6 decimal places in rewards
Originally, I wanted to use 3 decimal places. However, the screenshot from @patrickwoodhead showed a number `0.00031...`, which would be rendered as `0.0`. Therefore, we decided to use 6 decimal places instead.
I could not find any helper in ethers.js BigNumber class that would allow me to specify how many decimal places to show. I implemented the truncation myself using string manipulation.
=> feat: cleaner design of scheduled rewards

main/updater.js
Closes #137
Instead of showing different update states for when an update is available but not yet downloaded, download progress, and the update is available, this just changes it so that an update notification is shown once an update is downloaded and available. I don't think users care about in-between events, just want to know when they can restart to update.
=> Fix only show update when it is downloaded. Closes #137

main/tray.js
This is a more logical placement for me.
Before:
After:
I'm happy not to merge this if others disagree
=> tray: move up "Open Station"

.github/workflows/ci.yml
Windows builds are always failing in PRs. We should fix them, but for now let's just skip them to remove noise.
I created an issue to remind us to fix the builds: https://github.com/filecoin-station/desktop/issues/1323
=> ci: disable always failing windows pr builds

main/core.js, main/logs.js
Make it clear in code storing logs that chunks must be split at newlines.
My intention is to prevent regressions like the one fixed by #1319.
=> refactor: rename `logs.push()` to `logs.pushLine()`

main/logs.js
Often 100 lines aren't enough to find the error message, it has already been pushed out of the Array. We can easily keep 1000 lines.
@bajtos or should we raise the limit further? 5k or 10k lines?
=> logs: increase lines kept to 1000

main/index.js, main/typings.ts, main/wallet-backend.js
As discussed in https://filecoinproject.slack.com/archives/C03PVLW721L/p1709027221851889, we should migrate away from using Glif's GraphQL API. While we're at it, also migrate away from Filfox, as they don't offer an official API.
Don't merge this before we have received permission by Beryx/Zondax to use their API. If they don't give us permission, invalidate the token.
I've tested this PR and the API is smooth and responsive :)
=> Migrate from glif graphql & filfox to Beryx

main/updater.js
Ref https://filecoinproject.slack.com/archives/C03PVLW721L/p1709739129656009
=> updater: add retry `downloadUpdate()`

renderer/src/App.tsx, renderer/src/components/BaseLayout.tsx, renderer/src/components/Layout.tsx, renderer/src/components/Sidebar.tsx, renderer/src/pages/dashboard/Dashboard.tsx, renderer/src/test/wallet-interaction.test.tsx, renderer/src/test/wallet.test.tsx
See https://github.com/subvisual/desktop/pull/2
=> Add base layout

renderer/src/App.css, renderer/src/App.tsx, renderer/src/pages/settings/Settings.tsx
Add unstlyed settings page, with inputs for initial settings options.
This does not add the settings functionality, that will be done in a follow up PR (https://github.com/filecoin-station/desktop/pull/1498).
=> Add settings page

main/core.js, main/index.js, main/ipc.js, main/preload.js, main/settings.js, main/tray.js, main/typings.ts, renderer/src/lib/station-config.tsx, renderer/src/pages/settings/Settings.tsx, renderer/src/typings.ts
Add functionality to settings page:
- Adapt current settings that are in the top menu tray
- Add settings actions to ipcMain and preload
- Use settings actions in the Settings page
=> Connect settings page

renderer/src/App.tsx, renderer/src/lib/utils.ts, renderer/src/pages/wallet/ConfirmationDialog.tsx, renderer/src/pages/wallet/TransactionHistory.tsx, renderer/src/pages/wallet/TransferForm.tsx, renderer/src/pages/wallet/Wallet.tsx
Add unstyled content to Wallet page:
- Station address and balance info
- Tx history and currently processing tx.
- FIL transfer form (adapted from the current form). This allows updating the destination address and requesting the transfer, includes validation.
- Requesting the transfer opens a confirmation modal; on confirm it calls the `transferAllFundsToDestinationWallet` function.
=> Add wallet page content

package-lock.json, package.json
Bump [@filecoin-station/core](https://github.com/filecoin-station/core) from 20.5.1 to 20.5.2.
- [Release notes](https://github.com/filecoin-station/core/releases)
- [Commits](https://github.com/filecoin-station/core/compare/v20.5.1...v20.5.2)
=> deps: bump @filecoin-station/core from 20.5.1 to 20.5.2 (#1536)

renderer/src/pages/dashboard/Chart.tsx, renderer/src/pages/dashboard/ChartController.tsx, renderer/src/pages/dashboard/Dashboard.tsx, renderer/src/pages/dashboard/mockData.ts
- In the chart, adjust the scheduled rewards line to be relative to the total rewards received line.
- Add chart controls to filter historical data by time range.
- Improve the mock data generation, to have more data and more similar to the real data.
=> Add chart controls

.eslintrc.json, renderer/src/typings.ts
- fix the `indent` rule only applied to `renderer/` code
- type definitions weren't linted, this was ignored:
```ts
type foo = {
bar: string;
beep: string;
}
```
I noticed this seeing 4 spaces in https://github.com/filecoin-station/desktop/pull/1577/files#diff-d616452d0c127e14d1d82d22f58614e487a7d94e48fe57a165b528f8cc8c3581.
@bajtos merging now in order to update the v2 branch and not block Lange on it. Hindsight please 🙏
=> Fix indent more code consistently

package-lock.json, renderer/src/App.css, renderer/src/components/TextInput.tsx, renderer/src/components/TransactionStatusIndicator.tsx, renderer/src/components/Transition.tsx, renderer/src/pages/wallet/BalanceControl.tsx, renderer/src/pages/wallet/DestinationAddressForm.tsx, renderer/src/pages/wallet/EditDestinationAddressForm.tsx, renderer/src/pages/wallet/TransferWrapper.tsx, renderer/src/pages/wallet/Wallet.tsx, tailwind.config.js
Add transitions/animations to elements in the transfer flow. Does not include the bg grid, that will be in the next PR.
- Add a `Transition` component, for better control of elements that are animated
- Add transitions to global CSS, as this is easier to understand than doing it in tailwind classes.
- Some fixes in the `TextInput` component
- Add a dark mode to the transaction status indicator
=> Add transfer flow transitions

renderer/src/components/Button.tsx, renderer/src/components/DialogProvider.tsx, renderer/src/components/Sidebar.tsx, renderer/src/components/WalletWidget.tsx, renderer/src/lib/grid.ts, renderer/src/pages/dashboard/ActivityInfo.tsx, renderer/src/pages/dashboard/Dashboard.tsx, renderer/src/pages/modules/ModuleCard.tsx, renderer/src/pages/settings/Settings.tsx, renderer/src/pages/wallet/BalanceControl.tsx, renderer/src/pages/wallet/DestinationAddressForm.tsx, renderer/src/pages/wallet/EditDestinationAddressForm.tsx, renderer/src/pages/wallet/GridCanvas.tsx, renderer/src/pages/wallet/TransactionHistory.tsx, renderer/src/pages/wallet/TransferWrapper.tsx, renderer/src/pages/wallet/Wallet.tsx
- Some general styling fixes
- For the "open at login" switch, the initial value is true. Change it to undefined, to not flash from true to false if the options is actually disabled.
- Change element order in the wallet page, so when tabbing the focus goes to the transfer options before the tx history.
- Fix copy in the "confirm transfer" step.
- In the warped grid, ensure to render a flat grid when the destinationFIlAddress is not set
=> General fixes

renderer/src/hooks/StationRewards.tsx
Instead of only fetching historic rewards data when the app starts, refresh every 20 minutes (if the window is visible) or whenever the window becomes visible
=> Add update historic rewards

main/wallet-backend.js
Why:
- After starting transactions, there are sometimes runtime errors because the beryx response doesn't have a transactions property yet. This causes the tx to be reported as failed on the UI
How:
- Add an optional chaining in `convertEthTxHashToCid`
=> Prevent error in convertEthTxHashToCid

main/setup-sentry.js, renderer/src/components/Sentry.tsx
Old Station versions are producing too many un-actionable issues. We need to cut them off.
Related:
- #1606-
=> fix: rotate Sentry token

package-lock.json, package.json
Bump [@filecoin-station/core](https://github.com/filecoin-station/core) from 21.1.0 to 21.1.1.
- [Release notes](https://github.com/filecoin-station/core/releases/v21.1.1)
- [Commits](https://github.com/filecoin-station/core/compare/v21.1.0...v21.1.1)
=> deps: bump @filecoin-station/core from 21.1.0 to 21.1.1

renderer/src/pages/dashboard/RewardsInfo.tsx
We are paying them out every week, not every month.
Before my change:
=> fix: tooltip about scheduled rewards

renderer/src/pages/wallet/BalanceControl.tsx
Adjust font-size in wallet page balance display to account for more decimals.
=> Adjust balance font-size

renderer/src/pages/dashboard/Chart.tsx, renderer/src/pages/dashboard/chart-utils.ts
Fixes #1679 
- Add a warning when there are no records in the selected time range. Display "It seems you have no rewards accrued in the past 7 days | past month | past year | yet"
- Is there better copy for this?
=> Add no data screen

renderer/src/hooks/StationRewards.tsx, renderer/src/pages/dashboard/Chart.tsx
=> Add live scheduled rewards on current day. Closes #1677

renderer/src/pages/dashboard/Chart.tsx, renderer/src/pages/dashboard/chart-utils.ts
=> Chart: fix scheduled rewards on and after a payout

shared/typings.ts
This is a stop-gap solution to fix the CI.
I opened a GH issue in Station Core describing a more robust solution: 
- https://github.com/filecoin-station/core/issues/612
=> fix: typings import from Station Core

renderer/src/lib/utils.ts
Fixes:
This .0005 comes from multiplying by 1e18
The impact of this error is that scheduled rewards get shown as 0, therefore I'm going to merge and release before review.
=> formattedFilToBigInt: fix float to bigint error due to lack of precision
